#!/home/gym/.venvs/ctf/bin/python2
import os
import sys
from pwn import *
c = None
m = None

def main():
    #l = m.load_libc()
    #e = m.load_elf()

    c.interactive()

gdbs=[
    'c',
        ]
bp =[

        ]
if __name__ == "__main__":
    sys.path.append(os.path.expanduser('~/ctf/magicpwn'))
    try:
        from magicpwn import Magic
        # target: vm/native/remote
        # libc: vm/native/remote
        # config: path to config file
        # debug: gdb/villoc/gdbv/none
        m = Magic('vm', 'gdb', aslr=False, libc='local')
        #m = Magic('native', 'none', aslr=False, libc='remote')
        #m = Magic('native', 'villoc', aslr=False, libc='local')
        #m = Magic('remote', 'none', libc='remote')
        c = m.start(cmds=gdbs, bp=bp, ida=False)
    except ImportError:
        c = process("./chall")

    main()
